export const fakeHotelsData = [
  {
    id: 1,
    name: "فندق برج ساعة مكة الملكي",
    star_Number: 5,
    location: "إسم الحى، إسم الشارع، المدينة",
    rate: 4.5,
    rate_numbers: 371,
    rooms: [
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
    ],
  },
  {
    id: 1,
    name: "فندق برج ساعة مكة الملكي",
    star_Number: 5,
    location: "إسم الحى، إسم الشارع، المدينة",
    rate: 4.5,
    rate_numbers: 371,
    rooms: [
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
      {
        type: "غرفة عادية",
        price: 80,
        area: 140,
        bed_number: 4,
        available_bed: 2,
        bathroom_number: 2,
        features: ["تشمل الافطار و الغداء", "واى فاى مجانى"],
      },
    ],
  },
];