export const API_ROOT = process.env.NEXT_PUBLIC_API_URL;
export const RESERVATIONS_API_URL = process.env.NEXT_PUBLIC_RESERVATIONS_API_URL;
export const RESERVATIONS_ACCESS_KEY = process.env.NEXT_PUBLIC_RESERVATIONS_API_ACCESS_KEY;

